//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FormativaFinalJC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Alquiler
    {
        public int Id { get; set; }
        public int vehiculo { get; set; }
        public string cliente { get; set; }
        public int precio { get; set; }
        public int dias { get; set; }
    
        public virtual Vehiculo Vehiculo1 { get; set; }
    }
}
